version: '3.9'

services:
  backend:
    image: items-backend:1.0
    container_name: items-backend
    env_file:
      - ./backend/.env
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    networks:
      - myplayground-network

  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - myplayground-network

  frontend:
    image: item-frontend:3.0
    container_name: items-frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - myplayground-network    

networks:
  myplayground-network:
    driver: bridge

volumes:
  mongo-data:   
